[build]
  base = "services/Frontend"       # Netlify runs npm commands here
  publish = "dist"                 # relative to base, points to services/Frontend/dist
  command = "npm ci && npm run build"  # install dependencies and build

[build.environment]
  NODE_VERSION = "20.19.4"        # match your local Node version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
