[build]
  base = "services/Frontend"       # ensures Netlify runs npm commands in the correct folder
  publish = "services/Frontend/dist"
  command = "npm ci && npm run build"  # install dependencies before building

[build.environment]
  NODE_VERSION = "20.19.4"        # match your local Node version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
